name: Avisador Auto+


# PRUEBA AUTO+

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:
permissions:
  contents: write

jobs:

  comprobar:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar código2
        uses: actions/checkout@v5

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt
      
      - name: Ver archivo ejecutado
        run: |
          echo "CONTENIDO DE AUTO_PLUS.PY:"
          cat auto_plus.py
      
      - name: Revisar Auto+
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
        run: |
          python auto_plus.py
      - name: Guardar estado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add estado.txt
          git commit -m "Actualizar estado" || exit 0
          git push
